// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupRolloutPrefs.network.cookie.cookieBehavior", 4);
user_pref("app.normandy.user_id", "caf7302d-5514-401c-aac5-9d33a24d524f");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1568008609);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 3735);
user_pref("browser.cache.disk.capacity", 706560);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1568008589);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{3b773ba9-50fe-4e52-bf2f-f328b3146f8e}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1568008608691");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1568012208691");
user_pref("browser.search.region", "PH");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1568008601");
user_pref("browser.slowStartup.averageTime", 50986);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190718161435");
user_pref("browser.startup.homepage_override.mstone", "68.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1568008593);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1568008599799");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "68.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "c72a2fce099144daa543a9a7a953522b");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "68.0.1");
user_pref("extensions.lastPlatformVersion", "68.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"a79671c9-8900-4365-a09c-24e220e8a6b4\",\"fxmonitor@mozilla.org\":\"e26be225-0d59-421b-b098-a7fb955613cf\",\"screenshots@mozilla.org\":\"84294f7b-4239-41a4-af82-4d631439fd5d\",\"webcompat-reporter@mozilla.org\":\"de3ec9d9-93aa-4c04-b63e-0ddf7acf7524\",\"webcompat@mozilla.org\":\"523b955d-673f-4812-9c01-47abd48cca26\",\"default-theme@mozilla.org\":\"08443c60-7fa7-4ce0-9d5a-0741f48f20da\",\"google@search.mozilla.org\":\"b644c15f-f712-4ca2-bbd2-60a99d0f5848\",\"amazondotcom@search.mozilla.org\":\"27ae186c-caef-4525-97be-86ad57e2f3d8\",\"bing@search.mozilla.org\":\"818b2425-dc4a-46f2-b2fa-564c682f76e0\",\"ddg@search.mozilla.org\":\"bb2fc49b-ed98-487e-96be-98377efc51fc\",\"ebay@search.mozilla.org\":\"f55c0ea6-63fb-4550-9de6-4150fa7054f9\",\"twitter@search.mozilla.org\":\"ca5633bc-42ef-48aa-9b52-72201e805544\",\"wikipedia@search.mozilla.org\":\"2042e501-faed-4468-bf25-c037ee719010\"}");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1568008618);
user_pref("media.gmp-gmpopenh264.version", "1.8.1");
user_pref("media.gmp-manager.buildID", "20190718161435");
user_pref("media.gmp-manager.lastCheck", 1568008615);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "089a14b3-38d0-449a-85b7-60476a8ec786");
user_pref("security.sandbox.plugin.tempDirSuffix", "f16a7c36-3370-4e65-9cb5-1c29c2fa8ebc");
user_pref("services.blocklist.pinning.checked", 1568008615);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1567814407663\"");
user_pref("services.settings.last_update_seconds", 1568008615);
user_pref("services.settings.main.cfr-fxa.last_check", 1568008615);
user_pref("services.settings.main.cfr.last_check", 1568008615);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1568008615);
user_pref("services.settings.main.hijack-blocklists.last_check", 1568008615);
user_pref("services.settings.main.language-dictionaries.last_check", 1568008615);
user_pref("services.settings.main.normandy-recipes.last_check", 1568008615);
user_pref("services.settings.main.sites-classification.last_check", 1568008615);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1568008615);
user_pref("services.settings.security.onecrl.checked", 1568008615);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1568008547);
user_pref("toolkit.telemetry.cachedClientID", "2d4bc880-3571-4089-a80e-6403c431653a");
user_pref("toolkit.telemetry.previousBuildID", "20190718161435");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
